server:
  port: 7100
  servlet:
    context-path: /

# 日志配置
logging:
  level:
    com.hugai: debug
    org.springframework: warn

spring:
  # 数据库mysql
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.xa.DruidXADataSource
      url: jdbc:mysql://localhost:3306/db_hugai?useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
      username: root
      password: 123456
      initial-size: 5
      max-active: 20
      min-idle: 1
      max-wait: 10000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validationQuery: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filters: stat,wall,slf4j
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  # redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    database: 8
    password: 123456
    timeout: 10s
    Lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 20
        max-wait: -1ms
  mail:
    host: smtp.qq.com
    username: xxxxxx@qq.com
    password: xxxxxxx
    #端口号465或587
    port: 587
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: false
            required: false
        # 日志
        debug: false

# ---------------- 自定义配置
# 项目配置
project:
  file:
    # 上传文件最大大小 M
    maxUploadSize: 20
    # 文件名最大长度
    maxFileNameLength: 100
  # quartz定时任务配置
  quartz:
    # 定时任务白名单 仅允许访问的包名
    jobWhite: com.hugai
  # 事务配置
  tx:
    # 事务超时时间（秒）
    timeOut: 20
    # 开始事务路径表达式
    pointcutExpression: execution(* com.bebas.modules.**.service.impl.*ServiceImpl.*(..))
  # **** token配置
  token:
    # 令牌自定义标识
    header: Authorization
    # 令牌密钥
    secret: IMERpd1eC8ctB7sx73akVEgiNs0CNP
    # 令牌过期时间 毫秒
    expireTime: 172800000
    # 令牌刷新时间 毫秒
    flushToken: 3600000
  security:
    rsa:
      privateKey: MIICdQIBADANBgkqhkiG9w0BAQEFAASCAl8wggJbAgEAAoGBAJdCZe/iRlwYI04vLuGdk30nzMP/FswceLyEC6dsdVcYp/sseXbDn/BsgZBW5CmJFiAS6fLEugld9bAC130JoDKo4FM7S55rjMuk0d4IcCTb3iZzqBvTL/taRLsJsM378r9eOK9pcUhJK9i7wOttusD3+kQd72Wo0IAz0CDJt4krAgMBAAECgYBPVJ+qBH7qZi5+Hvjzk3V7OpiGYw9N1dDs7kQ+dv/Dwka30UeTJl6H9iCt1ySrNB7Ki6DvloYLy5/DxHnINngxyMRrFlwjZp+VnaGHxKd0EaxUnAHVR80k/qPPRTYXUHVzs0gPW5OP80oIDNjE8VeiF44iT+u3vLwDptWGPHyMAQJBAOW6c4OZCWE1fGgKcBi7gfJZ5Nrf75xmWcKyhX/OzIschMNFhESiFV8RawaP9vBolyRyWCFr8i4GwvYSM+vyc4ECQQCojq6hRSyKVW5NFNj9zYlukDcqzXdOg3dCeuXWlhetGYb0tsp48vtzbZyjVwP3KihIfc7718s+Gq4s11wBDWKrAkA1DZUlvA71eyOq51Yx8AO3k1kNzw+H//8UvqOj+38zVTe33PMJ4qCq3tvnnRG7PXxCN4Hw3fwE8xzNNTD2eXyBAkBHnZ/ay246NEQSIgp0A5Eh1cpquDO5uye/qkHfI5RZqp/pd4SdUPe/OlI0IDOCH3pQGowH+s7Syzk3uiTQGaTTAkBH8WZFXo9CFyXEVNQYUOxLSRshCdC1xEUxON9/ByPc2QonxJVNps0cljdj2jEKENWbFUbAI/ygn/MgjOYH0NAN
      publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCXQmXv4kZcGCNOLy7hnZN9J8zD/xbMHHi8hAunbHVXGKf7LHl2w5/wbIGQVuQpiRYgEunyxLoJXfWwAtd9CaAyqOBTO0uea4zLpNHeCHAk294mc6gb0y/7WkS7CbDN+/K/XjivaXFISSvYu8DrbbrA9/pEHe9lqNCAM9AgybeJKwIDAQAB
